import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'astro/config';

// Read JSON with fs instead of an import assertion — import assertions
// ("assert { type: 'json' }" / "with { type: 'json' }") behave inconsistently
// across Node versions and hosts.
const siteConfigPath = fileURLToPath(new URL('./src/data/site.json', import.meta.url));
const site = JSON.parse(readFileSync(siteConfigPath, 'utf-8'));

if (!site?.url || !/^https?:\/\//.test(site.url)) {
  throw new Error(
    `astro.config.mjs: "url" in src/data/site.json must be a full URL starting with http:// or https:// (got: ${JSON.stringify(site?.url)})`
  );
}

// ============================================================
// EVERYTHING here is pulled from src/data/site.json.
// Change the "url" field in site.json and rebuild — no code edits needed.
//
// NOTE: sitemap.xml is generated by our own endpoint at
// src/pages/sitemap.xml.ts instead of the @astrojs/sitemap package —
// that package had version-compatibility issues with this Astro version
// that caused unpredictable build failures. Our own endpoint has no
// external dependency and is much less likely to break on a host update.
// ============================================================
export default defineConfig({
  site: site.url, // e.g. "https://yourdomain.com"
  output: 'static'
});
